ALTER TABLE pins
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active',
ADD COLUMN IF NOT EXISTS posted_by TEXT,
ADD COLUMN IF NOT EXISTS access_level TEXT NOT NULL DEFAULT 'public';
